### PR TITLE
Add email to all admin trip tables

### LINKED ISSUE #332: Make all profile info show up when admin visits a profile from Trip
>Sørge for at hele profilen til brukeren vises når man trykker seg inn på en trip fra en destinasjon

**Time estimate:** 3 hours

### PR DESCRIPTION
**Pull request by essoen**
Resolves #332

### CODE REVIEW

**Comment by scbasma** [comment]
DENIED

**Comment by essoen** [comment]
pls

**Comment by scbasma** [comment]
ok. LGTM

**Review by scbasma — APPROVED** [review]
good stuff

**Comment by essoen** [comment]
ty my man

**Pull request merged**
